name: Build & Deploy
on: push
jobs:
  getVersion:
    name: Get version
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repo
        id: checkoutRepo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get commit ID
        id: getCommitId
        run: echo "::set-output name=commitId::$(git rev-parse --short=6 HEAD)"
      - name: Get version
        id: getVersion
        uses: PaulHatch/semantic-version@v4.0.2
        with:
          major_pattern: (semver:bump-major)
          minor_pattern: (semver:bump-minor)
      - name: Set version
        id: setVersion
        run: echo "version=${{steps.getVersion.outputs.major}}.${{steps.getVersion.outputs.minor}}.${{steps.getVersion.outputs.patch}}" >> $GITHUB_ENV
    outputs:
      version: ${{env.version}}
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: getVersion
    timeout-minutes: 5
    steps:
      - name: Checkout repo
        id: checkoutRepo
        uses: actions/checkout@v2
      - name: Set project version
        id: setProjectVersion
        run: npm --no-git-tag-version version ${{needs.getVersion.outputs.version}}
      - name: Build image
        id: buildImage
        run: docker build .
  deploy:
    name: Deploy
    if: ${{github.ref == 'refs/heads/main'}}
    runs-on: ubuntu-latest
    needs:
      - getVersion
      - build
    timeout-minutes: 10
    steps:
      - name: Checkout repo
        id: checkoutRepo
        uses: actions/checkout@v2
      - name: Set project version
        id: setProjectVersion
        run: npm --no-git-tag-version version ${{needs.getVersion.outputs.version}}
      - name: Deploy
        id: deploy
        env:
          RAILWAY_TOKEN: ${{secrets.RAILWAY_TOKEN}}
          NPM_CONFIG_PREFIX: ~/.npm-global
        run: >
          npm install -g @railway/cli@0.2.43 &&
          ~/.npm-global/bin/railway up
  pushVersionTag:
    name: Push version tag
    runs-on: ubuntu-latest
    needs:
      - getVersion
      - deploy
    timeout-minutes: 5
    steps:
      - name: Checkout repo
        id: checkoutRepo
        uses: actions/checkout@v2
      - name: Push version tag
        id: pushVersionTag
        run: >
          git tag v${{needs.getVersion.outputs.version}} &&
          git push origin v${{needs.getVersion.outputs.version}}
